# Generated by Django 3.0.7 on 2020-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200718_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='username1',
        ),
    ]
