# Generated by Django 3.0.7 on 2020-07-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200720_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='java',
            old_name='Quiestion',
            new_name='Question',
        ),
    ]
